version: "3"
services:
    front:
        build:
            context: ./
            dockerfile: "${DOCKERFILE}"
        ports:
            - "${FRONT_DEV_PORT}:3000"
        networks:
            - default
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules/
        stdin_open: true
    nginx:
        build:
            context: ./
            dockerfile: nginx.Dockerfile
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./build:/var/www
        networks:
            - default
        ports:
            - "${NGINX_PORT}:80"
networks:
    default:
        external:
            name: didiconfeita
